# Generated by Django 5.2.16 on 2026-08-02 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import launchpad.models.base


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Launchpad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive objects are excluded from normal use.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Stable code used by template tags, fixtures, and tests.",
                        max_length=80,
                        unique=True,
                        validators=[launchpad.models.base.validate_code],
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Human-friendly name.", max_length=120),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional renderer-neutral metadata.",
                        validators=[launchpad.models.base.validate_json_mapping],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who originally created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["title", "code"],
            },
        ),
        migrations.CreateModel(
            name="NavigationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive objects are excluded from normal use.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("authenticated", "Authenticated"),
                            ("staff", "Staff"),
                            ("superuser", "Superuser"),
                            ("private", "Private"),
                        ],
                        default="authenticated",
                        help_text="Base audience for this object. More specific users, groups, and permissions may further restrict visibility.",
                        max_length=20,
                    ),
                ),
                (
                    "permissions_required",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional list of Django permission strings, for example ['ancestry.view_person'].",
                        validators=[launchpad.models.base.validate_string_list],
                    ),
                ),
                (
                    "permissions_mode",
                    models.CharField(
                        choices=[
                            ("all", "Require all permissions"),
                            ("any", "Require any permission"),
                        ],
                        default="all",
                        help_text="Whether all listed permissions are required or any one of them is sufficient.",
                        max_length=10,
                    ),
                ),
                (
                    "visible_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional start time for visibility.",
                        null=True,
                    ),
                ),
                (
                    "visible_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional end time for visibility.",
                        null=True,
                    ),
                ),
                (
                    "visibility_rule",
                    models.CharField(
                        blank=True,
                        help_text="Optional registered runtime visibility rule. Blank means no additional runtime rule. This is a safe code, not a Python path.",
                        max_length=80,
                        validators=[launchpad.models.base.validate_code],
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Stable unique code used by fixtures, tests, and application logic. Do not change casually.",
                        max_length=80,
                        unique=True,
                        validators=[launchpad.models.base.validate_code],
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Primary display label.", max_length=100
                    ),
                ),
                (
                    "short_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional compact label for tight renderers.",
                        max_length=60,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional longer description.",
                        max_length=255,
                    ),
                ),
                (
                    "tooltip",
                    models.CharField(
                        blank=True, help_text="Optional tooltip text.", max_length=255
                    ),
                ),
                (
                    "aria_label",
                    models.CharField(
                        blank=True,
                        help_text="Optional accessibility label.",
                        max_length=255,
                    ),
                ),
                (
                    "cta_label",
                    models.CharField(
                        blank=True,
                        help_text="Optional call-to-action label for card-style renderers.",
                        max_length=60,
                    ),
                ),
                (
                    "url_type",
                    models.CharField(
                        choices=[("named", "Named Django URL"), ("raw", "Raw URL")],
                        default="named",
                        max_length=10,
                    ),
                ),
                (
                    "url_value",
                    models.CharField(
                        help_text="Django URL name when url_type=named, or raw URL when url_type=raw.",
                        max_length=255,
                    ),
                ),
                (
                    "url_args",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional positional arguments for named URLs. Values may contain context references such as '@user.username'.",
                        validators=[launchpad.models.base.validate_json_args],
                    ),
                ),
                (
                    "url_kwargs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional keyword arguments for named URLs. Values may contain context references such as '@context.person.pk'.",
                        validators=[launchpad.models.base.validate_json_mapping],
                    ),
                ),
                (
                    "query_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional query parameters appended after URL resolution.",
                        validators=[launchpad.models.base.validate_json_mapping],
                    ),
                ),
                (
                    "fragment",
                    models.CharField(
                        blank=True,
                        help_text="Optional URL fragment without '#'.",
                        max_length=100,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[("_self", "Same tab"), ("_blank", "New tab")],
                        default="_self",
                        max_length=10,
                    ),
                ),
                (
                    "rel",
                    models.CharField(
                        blank=True,
                        help_text="Optional rel attribute. New-tab links default to 'noopener noreferrer' when blank.",
                        max_length=120,
                    ),
                ),
                (
                    "download",
                    models.BooleanField(
                        default=False,
                        help_text="Whether renderers should mark this link as a download.",
                    ),
                ),
                (
                    "icon_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("fa", "FontAwesome"),
                            ("fe", "Feather"),
                            ("emoji", "Emoji"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="FontAwesome class or Feather icon name, depending on icon_type.",
                        max_length=120,
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        blank=True, help_text="Optional emoji icon.", max_length=16
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Disabled links may still render, but should not navigate.",
                    ),
                ),
                (
                    "disabled_reason",
                    models.CharField(
                        blank=True,
                        help_text="Optional explanation shown when enabled is false.",
                        max_length=255,
                    ),
                ),
                (
                    "active_match",
                    models.CharField(
                        choices=[
                            ("auto", "Automatic"),
                            ("none", "Never active"),
                            ("exact_path", "Exact path"),
                            ("path_prefix", "Path prefix"),
                            ("view_name", "View name"),
                            ("view_prefix", "View name prefix"),
                        ],
                        default="auto",
                        help_text="How this link should be marked active.",
                        max_length=20,
                    ),
                ),
                (
                    "active_path",
                    models.CharField(
                        blank=True,
                        help_text="Optional path used for exact-path or path-prefix matching.",
                        max_length=255,
                    ),
                ),
                (
                    "active_view_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional view name used for view-based active matching.",
                        max_length=255,
                    ),
                ),
                (
                    "search_aliases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional aliases for search or command-palette integrations.",
                        validators=[launchpad.models.base.validate_string_list],
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional renderer-neutral metadata.",
                        validators=[launchpad.models.base.validate_json_mapping],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who originally created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optional groups whose members may see this object. Permission gates still apply.",
                        related_name="%(app_label)s_%(class)s_visible_items",
                        to="auth.group",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optional explicit users who may see this object. Permission gates still apply.",
                        related_name="%(app_label)s_%(class)s_visible_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["title", "code"],
            },
        ),
        migrations.CreateModel(
            name="LaunchpadNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive objects are excluded from normal use.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("authenticated", "Authenticated"),
                            ("staff", "Staff"),
                            ("superuser", "Superuser"),
                            ("private", "Private"),
                        ],
                        default="authenticated",
                        help_text="Base audience for this object. More specific users, groups, and permissions may further restrict visibility.",
                        max_length=20,
                    ),
                ),
                (
                    "permissions_required",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional list of Django permission strings, for example ['ancestry.view_person'].",
                        validators=[launchpad.models.base.validate_string_list],
                    ),
                ),
                (
                    "permissions_mode",
                    models.CharField(
                        choices=[
                            ("all", "Require all permissions"),
                            ("any", "Require any permission"),
                        ],
                        default="all",
                        help_text="Whether all listed permissions are required or any one of them is sufficient.",
                        max_length=10,
                    ),
                ),
                (
                    "visible_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional start time for visibility.",
                        null=True,
                    ),
                ),
                (
                    "visible_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional end time for visibility.",
                        null=True,
                    ),
                ),
                (
                    "visibility_rule",
                    models.CharField(
                        blank=True,
                        help_text="Optional registered runtime visibility rule. Blank means no additional runtime rule. This is a safe code, not a Python path.",
                        max_length=80,
                        validators=[launchpad.models.base.validate_code],
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Optional stable code for this placement. Unique within a launchpad when provided.",
                        max_length=80,
                        validators=[launchpad.models.base.validate_code],
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("link", "Link"),
                            ("section", "Section"),
                            ("separator", "Separator"),
                        ],
                        default="link",
                        max_length=20,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Lower values render first among sibling nodes. Use gaps such as 1000, 2000, and 3000 to make later reordering easier.",
                    ),
                ),
                (
                    "title_override",
                    models.CharField(
                        blank=True,
                        help_text="Optional placement-specific title. For sections, this is the section label.",
                        max_length=120,
                    ),
                ),
                ("short_title_override", models.CharField(blank=True, max_length=60)),
                ("description_override", models.CharField(blank=True, max_length=255)),
                ("tooltip_override", models.CharField(blank=True, max_length=255)),
                ("aria_label_override", models.CharField(blank=True, max_length=255)),
                ("cta_label_override", models.CharField(blank=True, max_length=60)),
                (
                    "icon_type_override",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Use default"),
                            ("none", "None"),
                            ("fa", "FontAwesome"),
                            ("fe", "Feather"),
                            ("emoji", "Emoji"),
                        ],
                        default="",
                        help_text="Optional placement-specific icon type.",
                        max_length=10,
                    ),
                ),
                (
                    "icon_class_override",
                    models.CharField(
                        blank=True,
                        help_text="Optional placement-specific FontAwesome class or Feather name.",
                        max_length=120,
                    ),
                ),
                (
                    "emoji_override",
                    models.CharField(
                        blank=True,
                        help_text="Optional placement-specific emoji.",
                        max_length=16,
                    ),
                ),
                (
                    "enabled_override",
                    models.BooleanField(
                        blank=True,
                        help_text="Optional placement-specific enabled state. Blank uses the NavigationLink default.",
                        null=True,
                    ),
                ),
                (
                    "disabled_reason_override",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional renderer-neutral placement metadata.",
                        validators=[launchpad.models.base.validate_json_mapping],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who originally created this object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optional groups whose members may see this object. Permission gates still apply.",
                        related_name="%(app_label)s_%(class)s_visible_items",
                        to="auth.group",
                    ),
                ),
                (
                    "launchpad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="launchpad.launchpad",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional parent node. The parent must belong to the same launchpad.",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="children",
                        to="launchpad.launchpadnode",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optional explicit users who may see this object. Permission gates still apply.",
                        related_name="%(app_label)s_%(class)s_visible_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "navigation_link",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for link nodes. Empty for sections and separators.",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="placements",
                        to="launchpad.navigationlink",
                    ),
                ),
            ],
            options={
                "ordering": ["launchpad_id", "parent_id", "sort_order", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="navigationlink",
            index=models.Index(
                fields=["audience"], name="launchpad_n_audienc_c2aa93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="navigationlink",
            index=models.Index(
                fields=["url_type", "url_value"], name="launchpad_n_url_typ_f63742_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="launchpadnode",
            index=models.Index(
                fields=["launchpad", "parent", "sort_order"],
                name="launchpad_l_launchp_413942_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="launchpadnode",
            index=models.Index(
                fields=["launchpad", "kind"], name="launchpad_l_launchp_e7bf25_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="launchpadnode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("launchpad", "code"),
                name="launchpad_unique_node_code_per_launchpad",
            ),
        ),
        migrations.AddConstraint(
            model_name="launchpadnode",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "link"), ("navigation_link__isnull", False)),
                    models.Q(("kind", "section"), ("navigation_link__isnull", True)),
                    models.Q(("kind", "separator"), ("navigation_link__isnull", True)),
                    _connector="OR",
                ),
                name="launchpad_link_nodes_require_link",
            ),
        ),
    ]
